name: Deploy App

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'
          submodules: 'true'

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Install hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.155.2'
          extended: true

      - name: Build
        run: hugo --environment ${{ github.event.inputs.env }}
        working-directory: ./HugoBlog

      - name: Deploy
        run: aws s3 sync --delete ./public s3://${{ vars.AWS_BUCKET_NAME }}
        working-directory: ./HugoBlog

      - name: Invalidate cdn
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_DISTRIBUTION_ID }} --paths "/*"
        working-directory: ./HugoBlog
